name: main

on: [push]

jobs:
  pre:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

  build:
    needs: pre
    runs-on: ubuntu-latest
    container:
      image: akkyie/thesis
      env:
        TZ: Asia/Tokyo
      volumes:
        - $GITHUB_WORKSPACE:/thesis

    steps:
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make build && make -j2 redpen || true && .github/workflows/release.sh
