name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      uses: docker://akkyie/thesis
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: |
          make build &&
          make -j2 redpen || true &&
          .github/workflows/release.sh
